# Generated by Django 4.2.29 on 2026-05-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nb_personnel_requis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_radio', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=50)),
                ('kilometrage', models.IntegerField()),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Intervention', 'En intervention'), ('Indisponible', 'Indisponible')], max_length=20)),
                ('type_engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caserne.typeengin')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rapport', models.CharField(max_length=100)),
                ('type_sinistre', models.CharField(choices=[('Incendie', 'Incendie'), ('Accident', 'Accident'), ('Secours', 'Secours à personne')], max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('date_appel', models.DateTimeField()),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('vehicules', models.ManyToManyField(to='caserne.vehicule')),
            ],
        ),
    ]
