# Generated by Django 6.0.4 on 2026-05-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caserne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_revision', models.DateField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='caserne.vehicule')),
            ],
        ),
    ]
