# Generated by Django 6.0.4 on 2026-05-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caserne', '0002_intervention_notes_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='type_engin',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('FPT', 'Fourgon Pompe Tonne'), ('VSAV', 'Véhicule de Secours et d’Assistance aux Victimes'), ('EPA', 'Échelle Pivotante Automatique')], default='FPT', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeEngin',
        ),
    ]
